/**
 * Workspace icon keys (./iconLibrary.js) mapped to their Phosphor components.
 * Each icon is a named import, so the production build keeps only these.
 * (Infinity is renamed so it does not shadow the global.)
 */
import {
  Anchor,
  Article,
  Atom,
  Backpack,
  Bank,
  Barbell,
  Basketball,
  BookOpen,
  BookOpenText,
  Bookmark,
  Books,
  Brain,
  Briefcase,
  Bug,
  Buildings,
  Butterfly,
  Calculator,
  CalendarBlank,
  Camera,
  Carrot,
  CastleTurret,
  Certificate,
  Chalkboard,
  ChalkboardTeacher,
  ChartBar,
  ChartLine,
  ChartLineUp,
  ChartPie,
  ChatText,
  Circuitry,
  ClipboardText,
  Cloud,
  Coffee,
  Coins,
  Compass,
  CompassTool,
  Cpu,
  Crown,
  Cube,
  CurrencyDollar,
  Database,
  DeviceMobile,
  DiceFive,
  Dna,
  Exam,
  Feather,
  FileCode,
  FilmSlate,
  FirstAidKit,
  Flag,
  Flame,
  Flask,
  Folder,
  GameController,
  Gavel,
  GitBranch,
  Globe,
  GlobeHemisphereWest,
  GraduationCap,
  Graph,
  Guitar,
  Handshake,
  Heart,
  Heartbeat,
  Hourglass,
  Infinity as InfinityIcon,
  Intersect,
  Laptop,
  Leaf,
  Lightbulb,
  Lightning,
  Magnet,
  MapTrifold,
  MaskHappy,
  Megaphone,
  MicrophoneStage,
  Microscope,
  Mountains,
  MusicNotes,
  Newspaper,
  Notebook,
  PaintBrush,
  PaintBucket,
  Palette,
  PenNib,
  PencilLine,
  PersonSimpleRun,
  Pi,
  PianoKeys,
  PiggyBank,
  Pill,
  Planet,
  Plant,
  Polygon,
  PresentationChart,
  PuzzlePiece,
  Quotes,
  Receipt,
  Robot,
  Rocket,
  Ruler,
  Scales,
  Scissors,
  Scroll,
  Shapes,
  ShieldCheck,
  SoccerBall,
  Star,
  Stethoscope,
  Storefront,
  Student,
  Sun,
  Syringe,
  Target,
  TerminalWindow,
  TestTube,
  TextAa,
  Tooth,
  Translate,
  Tree,
  Trophy,
  Users,
  UsersThree,
  Virus,
} from "@phosphor-icons/react";

export const WORKSPACE_ICON_COMPONENTS = {
  atom: Atom,
  dna: Dna,
  flask: Flask,
  "test-tube": TestTube,
  microscope: Microscope,
  planet: Planet,
  magnet: Magnet,
  leaf: Leaf,
  plant: Plant,
  tree: Tree,
  butterfly: Butterfly,
  virus: Virus,
  lightning: Lightning,
  calculator: Calculator,
  pi: Pi,
  infinity: InfinityIcon,
  intersect: Intersect,
  "dice-five": DiceFive,
  ruler: Ruler,
  "compass-tool": CompassTool,
  polygon: Polygon,
  cube: Cube,
  "chart-line": ChartLine,
  "chart-bar": ChartBar,
  "chart-pie": ChartPie,
  graph: Graph,
  "book-open": BookOpen,
  "book-open-text": BookOpenText,
  books: Books,
  notebook: Notebook,
  "pencil-line": PencilLine,
  "pen-nib": PenNib,
  feather: Feather,
  translate: Translate,
  "text-aa": TextAa,
  quotes: Quotes,
  article: Article,
  "chat-text": ChatText,
  globe: Globe,
  "globe-hemisphere-west": GlobeHemisphereWest,
  "map-trifold": MapTrifold,
  compass: Compass,
  mountains: Mountains,
  scroll: Scroll,
  bank: Bank,
  crown: Crown,
  "castle-turret": CastleTurret,
  newspaper: Newspaper,
  hourglass: Hourglass,
  anchor: Anchor,
  "paint-brush": PaintBrush,
  palette: Palette,
  "paint-bucket": PaintBucket,
  shapes: Shapes,
  scissors: Scissors,
  camera: Camera,
  "film-slate": FilmSlate,
  "mask-happy": MaskHappy,
  "music-notes": MusicNotes,
  "piano-keys": PianoKeys,
  guitar: Guitar,
  "microphone-stage": MicrophoneStage,
  "file-code": FileCode,
  "terminal-window": TerminalWindow,
  cpu: Cpu,
  circuitry: Circuitry,
  robot: Robot,
  database: Database,
  cloud: Cloud,
  laptop: Laptop,
  "device-mobile": DeviceMobile,
  "git-branch": GitBranch,
  bug: Bug,
  "shield-check": ShieldCheck,
  "game-controller": GameController,
  briefcase: Briefcase,
  scales: Scales,
  gavel: Gavel,
  handshake: Handshake,
  buildings: Buildings,
  storefront: Storefront,
  "currency-dollar": CurrencyDollar,
  coins: Coins,
  "piggy-bank": PiggyBank,
  "chart-line-up": ChartLineUp,
  megaphone: Megaphone,
  receipt: Receipt,
  heartbeat: Heartbeat,
  "first-aid-kit": FirstAidKit,
  stethoscope: Stethoscope,
  pill: Pill,
  syringe: Syringe,
  tooth: Tooth,
  brain: Brain,
  carrot: Carrot,
  barbell: Barbell,
  "person-simple-run": PersonSimpleRun,
  "soccer-ball": SoccerBall,
  basketball: Basketball,
  "graduation-cap": GraduationCap,
  chalkboard: Chalkboard,
  "chalkboard-teacher": ChalkboardTeacher,
  student: Student,
  users: Users,
  "users-three": UsersThree,
  exam: Exam,
  certificate: Certificate,
  backpack: Backpack,
  "clipboard-text": ClipboardText,
  "calendar-blank": CalendarBlank,
  "presentation-chart": PresentationChart,
  folder: Folder,
  star: Star,
  lightbulb: Lightbulb,
  rocket: Rocket,
  bookmark: Bookmark,
  "puzzle-piece": PuzzlePiece,
  target: Target,
  trophy: Trophy,
  flag: Flag,
  heart: Heart,
  flame: Flame,
  sun: Sun,
  coffee: Coffee,
};
