apiVersion: v2
name: missionllm
description: Mission LLM by Sigmatech, the all-in-one AI application with built-in RAG, AI agents, No-code agent builder, MCP compatibility, and more.
type: application
version: 1.0.0
appVersion: "1.85.0"